### ISSUE TITLE
Exposed filesystem in production

### ISSUE THREAD

**Issue by defvoid** [faceyspacey/flush-chunks-boilerplate-webpack-chunknames#1]
It seems the filesystem is still exposed in production. Same goes for `flush-chunks-boilerplate-webpack` even though it uses `webpack.HashedModuleIdsPlugin()`.

**Comment by faceyspacey** [comment]
Your wish has been granted. React Hot Loader was running in production, which also displays module paths.

**Comment by defvoid** [comment]
Great! The no_css.js files are okey. However it is still exposed in the .js files.

**Comment by faceyspacey** [comment]
Confirmed.

That's a challenging one. I'd think it would be the other way around and the `.no_css.js` files were the ones not getting fully transformed since they are the ones I clone and do something different than normal with:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/index.js#L367

...I'm hoping this is some easy fix in configuration I'm missing, as the plugin is very difficult to work with.

**Comment by faceyspacey** [comment]
well, i found the issue. it's been a while since i made. it's in fact the `.js` files where im doing more work, since im changing them to have custom style injection even tho the css-related stuff was meant to be stripped out. i manually re-add the code that uses style-loader. i'll probably be able to get a fix out for this soon (hopefully before something ur building with it reaches production ;))

**Comment by faceyspacey** [comment]
Just so you know we're going to go a different better direction. I've made a babel plugin that transforms `import()` into `Promise.all([import(), fetchCss()])`. 

There have been speed issues in compilation, and not having to create `no_css.js` files is a big win. 

It's also a big win in that now development is identical to production: you always embed your stylesheets in the DOM. That means less unforeseen problems taking your app to production. There is no more style-loader usage. The spreadsheets simply update as new ones come over the wire in HMR.

So this will eliminate all issues related to exposing your file system in js chunks since we barely touch them (we only inject public css file names in the `module.hot.accept` code for HMR).

Thoughts?
